/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new chunked upload session.
         * @description Registers a new upload session for a source .obj file. Rejects the request up front (4xx) if the declared size exceeds 500MB or the filename extension is not an accepted 3D model format (.obj).
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier returned by POST /api/uploads. */
                id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        /** Get upload session status (for resume/status checks). */
        get: operations["getUploadStatus"];
        put?: never;
        post?: never;
        /** Abort an upload session and delete any received temp parts. */
        delete: operations["abortUpload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/parts/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier returned by POST /api/uploads. */
                id: components["parameters"]["UploadId"];
                /** @description 1-based chunk/part number within the upload session. */
                n: number;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Upload a single chunk/part of the file.
         * @description Body is the raw bytes of the chunk. The `X-Chunk-SHA256` header must carry the SHA-256 checksum (lowercase hex) of the chunk body for integrity verification.
         *     **Body size constraint:** this route enforces a hard 16MB limit on the request body. This is documented here as a contract-level constraint but is not (and cannot be) declaratively expressed by an OpenAPI 3.1 `requestBody` schema for raw binary bodies; the actual limit must be enforced at the transport/reverse-proxy or server middleware layer (e.g. a body-size-limiting middleware in front of the handler), which returns 413 if exceeded.
         */
        put: operations["uploadPart"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier returned by POST /api/uploads. */
                id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize an upload session and enqueue transcoding.
         * @description Validates that the supplied part set is complete (covers every expected part number with no gaps) and contiguous, and that each part's etag matches what the server recorded. On success, the source file is assembled, a model record is created, and transcoding is queued.
         */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public shareable slug identifying the transcoded model. */
                slug: components["parameters"]["ModelSlug"];
            };
            cookie?: never;
        };
        /**
         * Get the model manifest (the viewer's single entry point).
         * @description Returns the current status, progress, geometry stats, camera framing, and LOD asset list for a model. While `status` is `queued` or `processing`, `lods` is an empty array and `bounds`/ `camera` may be `null`. While `failed`, `error` carries a machine-readable code and message.
         */
        get: operations["getModelManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{slug}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public shareable slug identifying the transcoded model. */
                slug: components["parameters"]["ModelSlug"];
            };
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of transcode status/progress.
         * @description Emits a stream of `text/event-stream` events while the model is `queued` or `processing`, so the viewer can update progress without polling. Each event's `data` payload is a JSON object shaped like `{ "status": ModelStatus, "progress": { "stage": string, "percent": number }, "error": ProblemDetails | null }`. The server closes the stream once `status` reaches a terminal state (`ready` or `failed`).
         */
        get: operations["streamModelEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{slug}/assets/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public shareable slug identifying the transcoded model. */
                slug: components["parameters"]["ModelSlug"];
                /** @description Asset filename as referenced by the manifest's `lods[].url` (e.g. `lod0.glb`). */
                asset: string;
            };
            cookie?: never;
        };
        /**
         * Fetch a LOD GLB asset for the model.
         * @description Returns meshopt-compressed GLB bytes for the requested LOD level. Supports HTTP range requests (partial content) and conditional requests via `If-None-Match`. Assets are immutable once a model reaches `ready` status and should be served with a long-lived, immutable `Cache-Control` header.
         */
        get: operations["getModelAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{slug}/original": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public shareable slug identifying the transcoded model. */
                slug: components["parameters"]["ModelSlug"];
            };
            cookie?: never;
        };
        /** Download the original uploaded .obj file. */
        get: operations["getModelOriginal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/health check. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUploadRequest: {
            /**
             * @description Original filename, including extension (must be .obj).
             * @example scan.obj
             */
            filename: string;
            /** @description Declared total size of the file in bytes. Rejected if it exceeds 500MB (524288000 bytes). */
            size_bytes: number;
            /**
             * @description Optional client-declared MIME type (advisory only; server validates by extension).
             * @example text/plain
             */
            content_type?: string;
            /** @description Optional lowercase hex SHA-256 of the full file, for end-to-end integrity verification. */
            client_sha256?: string;
        };
        UploadSession: {
            /** @description Identifier for the created upload session, used in subsequent part/status/complete/abort calls. */
            upload_id: string;
            /**
             * @description Recommended/required chunk size in bytes for PUT part uploads (must not exceed the 16MB per-part limit).
             * @example 8388608
             */
            chunk_size: number;
            /**
             * @description Maximum number of parts the client may upload concurrently.
             * @example 4
             */
            max_concurrency: number;
            /**
             * Format: date-time
             * @description Timestamp after which the upload session and any received parts are discarded.
             */
            expires_at: string;
        };
        PartAck: {
            part_number: number;
            /** @description Server-assigned identifier for this stored part, to be echoed back in the complete request. */
            etag: string;
            /** @description Size in bytes of the stored part, as received. */
            size: number;
        };
        UploadStatus: {
            /**
             * @description Current state of the upload session itself (distinct from model transcode status).
             * @enum {string}
             */
            status: "pending" | "completed" | "aborted" | "expired";
            /** @description Sorted list of part numbers successfully received so far. */
            received_parts: number[];
            /** @description Total bytes received across all parts so far. */
            bytes_received: number;
            /** Format: date-time */
            expires_at: string;
        };
        CompleteUploadRequest: {
            /** @description Complete, contiguous list of parts in order, as acknowledged by prior PUT requests. */
            parts: {
                /** @description Part number. */
                n: number;
                /** @description Etag returned by the server when this part was uploaded. */
                etag: string;
            }[];
        };
        CompleteUploadResponse: {
            /** @description Internal identifier for the created model record. */
            model_id: string;
            /** @description Public shareable slug for the model (used in GET /api/models/{slug}). */
            share_slug: string;
            /**
             * Format: uri
             * @description Fully-qualified shareable URL for viewing the model.
             */
            share_url: string;
            status: components["schemas"]["ModelStatus"];
        };
        /**
         * @description Lifecycle status of a model's transcode job.
         * @enum {string}
         */
        ModelStatus: "queued" | "processing" | "ready" | "failed";
        Progress: {
            /**
             * @description Human/machine-readable name of the current transcode stage (e.g. `parsing`, `decimating`, `compressing`, `done`).
             * @example compressing
             */
            stage: string;
            /** @description Overall completion percentage across all stages. */
            percent: number;
        };
        Stats: {
            /** @description Size in bytes of the original uploaded .obj file. */
            source_bytes?: number;
            /** @description Vertex count of the source mesh. */
            vertices?: number;
            /** @description Triangle count of the source mesh. */
            triangles?: number;
        };
        Bounds: {
            /** @description Axis-aligned bounding box minimum corner [x, y, z]. */
            min: number[];
            /** @description Axis-aligned bounding box maximum corner [x, y, z]. */
            max: number[];
            /** @description Bounding box center [x, y, z]. */
            center: number[];
            /** @description Bounding sphere radius encompassing the model. */
            radius: number;
        };
        Camera: {
            /** @description Suggested initial camera position [x, y, z]. */
            position: number[];
            /** @description Suggested initial camera look-at target [x, y, z]. */
            target: number[];
            /** @description Suggested near clipping plane distance. */
            near: number;
            /** @description Suggested far clipping plane distance. */
            far: number;
        };
        LodDescriptor: {
            /** @description LOD level, 0 being the lowest-detail/first-loaded asset in the progressive ladder. */
            level: number;
            /**
             * @description Path to fetch this LOD's GLB asset, resolvable against GET /api/models/{slug}/assets/{asset}.
             * @example /api/models/7Kq2mV9pLx4RtZ0aBcDeFg/assets/lod0.glb
             */
            url: string;
            /** @description Triangle count of this LOD's mesh. */
            triangles: number;
            /** @description Size in bytes of this LOD's GLB asset. */
            byte_length: number;
        };
        ModelManifest: {
            /** @example 7Kq2mV9pLx4RtZ0aBcDeFg */
            slug: string;
            status: components["schemas"]["ModelStatus"];
            /**
             * @description Original uploaded filename.
             * @example scan.obj
             */
            filename: string;
            /** Format: date-time */
            created_at: string;
            progress: components["schemas"]["Progress"];
            /** @description Machine-readable error info when status is `failed`; `null` otherwise. */
            error: components["schemas"]["ProblemDetails"] | null;
            /** @description Geometry/source statistics; may be absent or `null` until available. */
            stats?: components["schemas"]["Stats"] | null;
            /** @description Bounding volume; `null` while `queued`/`processing`. */
            bounds?: components["schemas"]["Bounds"] | null;
            /** @description Suggested initial camera framing; `null` while `queued`/`processing`. */
            camera?: components["schemas"]["Camera"] | null;
            /** @description Progressive LOD ladder, ordered by ascending `level`. Empty while `queued`/`processing`. */
            lods: components["schemas"]["LodDescriptor"][];
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /**
             * @description Deployed application/build version.
             * @example 1.4.2
             */
            version: string;
        };
        /** @description RFC 9457 problem details object, used for all error responses. */
        ProblemDetails: {
            /**
             * Format: uri-reference
             * @description A URI identifying the problem type. May be relative/short-form. See the ProblemType enum for the stable set of values used by this API.
             * @example urn:model-viewer:upload-too-large
             */
            type: string;
            /**
             * @description Short, human-readable summary of the problem type.
             * @example Uploaded file exceeds the maximum allowed size.
             */
            title: string;
            /**
             * @description HTTP status code repeated for convenience.
             * @example 413
             */
            status: number;
            /** @description Human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description Optional URI identifying this specific occurrence of the problem.
             */
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Stable set of `type` URI values used in ProblemDetails responses across this API. Additional types may be added over time; clients should treat unrecognized values as generic errors.
         * @enum {string}
         */
        ProblemType: "urn:model-viewer:upload-too-large" | "urn:model-viewer:bad-extension" | "urn:model-viewer:upload-not-found" | "urn:model-viewer:upload-expired" | "urn:model-viewer:upload-incomplete" | "urn:model-viewer:upload-part-mismatch" | "urn:model-viewer:chunk-checksum-mismatch" | "urn:model-viewer:chunk-too-large" | "urn:model-viewer:model-not-found" | "urn:model-viewer:transcode-failed" | "urn:model-viewer:range-not-satisfiable" | "urn:model-viewer:rate-limited" | "urn:model-viewer:queue-saturated";
    };
    responses: never;
    parameters: {
        /** @description Upload session identifier returned by POST /api/uploads. */
        UploadId: string;
        /** @description Public shareable slug identifying the transcoded model. */
        ModelSlug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSession"];
                };
            };
            /** @description Bad extension, missing/invalid fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Declared size exceeds the 500MB limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Upload/transcode queue saturated; try again later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getUploadStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier returned by POST /api/uploads. */
                id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current upload session status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadStatus"];
                };
            };
            /** @description Upload session not found or expired. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    abortUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier returned by POST /api/uploads. */
                id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload session aborted and temp parts deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upload session not found or expired. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    uploadPart: {
        parameters: {
            query?: never;
            header: {
                /** @description Lowercase hex-encoded SHA-256 checksum of the chunk body. */
                "X-Chunk-SHA256": string;
            };
            path: {
                /** @description Upload session identifier returned by POST /api/uploads. */
                id: components["parameters"]["UploadId"];
                /** @description 1-based chunk/part number within the upload session. */
                n: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Chunk accepted and stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartAck"];
                };
            };
            /** @description Checksum mismatch or malformed part number. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Upload session not found or expired. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Chunk body exceeds the 16MB per-part limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier returned by POST /api/uploads. */
                id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadRequest"];
            };
        };
        responses: {
            /** @description Upload finalized; model created and queued for transcoding. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteUploadResponse"];
                };
            };
            /** @description Incomplete or mismatched part set (gaps, wrong etags, extra parts). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Upload session not found or expired. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Transcode queue saturated; try again later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModelManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public shareable slug identifying the transcoded model. */
                slug: components["parameters"]["ModelSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model manifest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelManifest"];
                };
            };
            /** @description Model not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    streamModelEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public shareable slug identifying the transcoded model. */
                slug: components["parameters"]["ModelSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream opened. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Model not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModelAsset: {
        parameters: {
            query?: never;
            header?: {
                /** @description Standard HTTP Range header for partial content requests. */
                Range?: string;
                /** @description ETag for conditional requests. */
                "If-None-Match"?: string;
            };
            path: {
                /** @description Public shareable slug identifying the transcoded model. */
                slug: components["parameters"]["ModelSlug"];
                /** @description Asset filename as referenced by the manifest's `lods[].url` (e.g. `lod0.glb`). */
                asset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full asset bytes. */
            200: {
                headers: {
                    ETag?: string;
                    /** @description e.g. `public, max-age=31536000, immutable`. */
                    "Cache-Control"?: string;
                    "Content-Length"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "model/gltf-binary": string;
                };
            };
            /** @description Partial content, satisfying the Range request. */
            206: {
                headers: {
                    ETag?: string;
                    "Content-Range"?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "model/gltf-binary": string;
                };
            };
            /** @description Not modified (ETag matched `If-None-Match`). */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Model or asset not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Range not satisfiable. */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModelOriginal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public shareable slug identifying the transcoded model. */
                slug: components["parameters"]["ModelSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original .obj bytes. */
            200: {
                headers: {
                    /** @description e.g. `attachment; filename="scan.obj"`. */
                    "Content-Disposition"?: string;
                    "Content-Length"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Model not found, or original not available (e.g. purged). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
