//! Synthetic `.obj` generator for performance/load testing.
//!
//! Produces a simple, valid, repeatable tessellated-plane mesh (a grid of
//! quads split into triangles, sharing one constant vertex normal) streamed
//! directly to disk row-by-row until the output file reaches roughly the
//! requested size. It intentionally does not try to hit the target byte
//! count exactly -- it only needs to be in the right ballpark (e.g. ~1MB,
//! ~100MB, ~600MB) for load testing.
//!
//! No external crates are used, so this can be run either via Cargo:
//!
//! ```text
//! cargo run --release --manifest-path fixtures/Cargo.toml -- fixtures/large/1mb.obj 1MB
//! ```
//!
//! or as a standalone script via rustc:
//!
//! ```text
//! rustc -O fixtures/generate.rs -o /tmp/generate
//! /tmp/generate fixtures/large/1mb.obj 1MB
//! ```
//!
//! Accepted size formats: a plain byte count (`1048576`), or a number with a
//! `K`/`KB`, `M`/`MB`, or `G`/`GB` suffix (case-insensitive), e.g. `1MB`,
//! `100MB`, `600MB`.

use std::env;
use std::fs::File;
use std::io::{self, BufWriter, Write};
use std::path::Path;
use std::process::ExitCode;

/// Number of vertices per row of the generated grid. The grid grows in the
/// row (Y) direction only, adding rows until the target size is reached.
const GRID_WIDTH: usize = 256;

/// Wraps a `Write` implementor and counts bytes written through it, so we
/// know when we've produced roughly `target_bytes` without needing to seek
/// or stat the file.
struct CountingWriter<W: Write> {
    inner: W,
    count: u64,
}

impl<W: Write> CountingWriter<W> {
    fn new(inner: W) -> Self {
        Self { inner, count: 0 }
    }
}

impl<W: Write> Write for CountingWriter<W> {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        let n = self.inner.write(buf)?;
        self.count += n as u64;
        Ok(n)
    }

    fn flush(&mut self) -> io::Result<()> {
        self.inner.flush()
    }
}

/// Parses a human-friendly size string like `1MB`, `100mb`, `600M`, or a
/// plain byte count like `1048576` into a byte count.
fn parse_size(s: &str) -> Result<u64, String> {
    let trimmed = s.trim();
    let lower = trimmed.to_ascii_lowercase();

    let (num_part, mult): (&str, u64) = if let Some(n) = lower
        .strip_suffix("gb")
        .or_else(|| lower.strip_suffix('g'))
    {
        (n, 1024 * 1024 * 1024)
    } else if let Some(n) = lower.strip_suffix("mb").or_else(|| lower.strip_suffix('m')) {
        (n, 1024 * 1024)
    } else if let Some(n) = lower.strip_suffix("kb").or_else(|| lower.strip_suffix('k')) {
        (n, 1024)
    } else {
        (lower.as_str(), 1)
    };

    let num: f64 = num_part
        .trim()
        .parse()
        .map_err(|_| format!("invalid size: '{s}' (expected e.g. 1MB, 100MB, 600MB, or a byte count)"))?;

    if num < 0.0 {
        return Err(format!("size must not be negative: '{s}'"));
    }

    Ok((num * mult as f64) as u64)
}

fn main() -> ExitCode {
    let args: Vec<String> = env::args().collect();
    if args.len() != 3 {
        eprintln!(
            "usage: {} <output.obj> <target-size>  (e.g. 1MB, 100MB, 600MB, or a raw byte count)",
            args.first().map(String::as_str).unwrap_or("generate")
        );
        return ExitCode::FAILURE;
    }

    let out_path = &args[1];
    let target_bytes = match parse_size(&args[2]) {
        Ok(b) if b > 0 => b,
        Ok(_) => {
            eprintln!("target size must be greater than zero");
            return ExitCode::FAILURE;
        }
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };

    match generate(Path::new(out_path), target_bytes) {
        Ok(written) => {
            println!(
                "wrote {out_path} (~{written} bytes, target ~{target_bytes} bytes)"
            );
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("failed to generate {out_path}: {e}");
            ExitCode::FAILURE
        }
    }
}

/// Streams a tessellated-plane mesh to `path`, growing row by row until the
/// running byte count reaches `target_bytes`. Returns the actual number of
/// bytes written.
fn generate(path: &Path, target_bytes: u64) -> io::Result<u64> {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }

    let file = File::create(path)?;
    let buffered = BufWriter::with_capacity(1 << 20, file);
    let mut w = CountingWriter::new(buffered);

    writeln!(w, "# Synthetic tessellated-plane mesh generated by fixtures/generate.rs")?;
    writeln!(w, "# Grid width: {GRID_WIDTH} vertices/row; target size ~{target_bytes} bytes")?;
    // The plane is flat, so every vertex shares the same normal.
    writeln!(w, "vn 0.000000 0.000000 1.000000")?;

    const SPACING: f64 = 1.0;
    let width = GRID_WIDTH;
    let mut row: usize = 0;

    loop {
        for col in 0..width {
            let x = col as f64 * SPACING;
            let y = row as f64 * SPACING;
            writeln!(w, "v {x:.6} {y:.6} {:.6}", 0.0)?;
        }

        if row > 0 {
            // Connect the previous row to this row: two triangles per cell.
            let prev_base = (row - 1) * width;
            let curr_base = row * width;
            for col in 0..width - 1 {
                let a = prev_base + col + 1; // OBJ indices are 1-based
                let b = prev_base + col + 2;
                let c = curr_base + col + 1;
                let d = curr_base + col + 2;
                writeln!(w, "f {a}//1 {b}//1 {c}//1")?;
                writeln!(w, "f {b}//1 {d}//1 {c}//1")?;
            }
        }

        row += 1;

        if w.count >= target_bytes {
            break;
        }
    }

    w.flush()?;
    Ok(w.count)
}
