[package]
name = "model-api"
version.workspace = true
edition.workspace = true

[[bin]]
name = "hello"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
model-core = { workspace = true }
model-transcode = { workspace = true }
model-storage = { workspace = true }
